---
title: "Final Project Version 2.0"
---

## Libraries

```{r}
#| echo: false
#| output: false
#| warning: false

library(tidyverse)
library(ggplot2)
library(dplyr)
library(viridis)
library(plotly)
```

## Dataset

```{r}
twitch <- read.csv("D:/rstudio/final_project_version02/twitch.csv")
twitch <- twitch |>
  rename(
    channel = Channel,
    watch_time_mins = Watch.time.Minutes.,
    stream_time_mins = Stream.time.minutes.,
    peak_view_count = Peak.viewers,
    avg_view_count = Average.viewers,
    follower_count = Followers,
    follower_gain_count = Followers.gained,
    view_gain_count = Views.gained,
    partnered = Partnered,
    mature = Mature,
    language = Language
  )
```

```{r}
head(twitch)
```

```{r}
str(twitch)
```

## Subquestion One

Are the means of watch time significantly different between Twitch streamers who have mature content versus those who do not?

```{r}

G_twitch_streamers <- twitch |>
  filter(`mature` == "False")

R18_twitch_streamers <- twitch |>
  filter(`mature` == "True")

t.test(G_twitch_streamers$watch_time_mins, R18_twitch_streamers$watch_time_mins)
```

## Subquestion Two

```{r}
language_twitch <- twitch %>%
  group_by(language) %>%   # Group the data by the language column
  summarise(count = n())

language_twitch
```

## Basic piechart

```{r}
ggplot(language_twitch, aes(x="", y=count, fill=language)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  # scale_color_viridis() +
  # scale_fill_viridis() +
  
  theme_void() # remove background, grid, numeric labels

```

```{r}
print(colnames(twitch))
```

## Subquestion Three

### Linear Regression Model

```{r}
q3_lm_model_01 <- lm(log(follower_gain_count) ~ view_gain_count + language + stream_time_mins, data=twitch)
print(q3_lm_model_01)
```

```{r}
summary(q3_lm_model_01)
```

### Residual Plot

```{r}
# Creating a dataframe of residuals and fitted values
q3_resid_df_01 <- data.frame(
  Fitted = fitted(q3_lm_model_01),
  Residuals = resid(q3_lm_model_01)
)

ggplot(q3_resid_df_01, aes(x=Fitted, y=Residuals)) +
  geom_point() +
  geom_smooth(method="lm", se=FALSE, color="blue") +
  labs(x="Fitted Values", y="Residuals", title="Residual vs. Fitted Plot") +
  theme_minimal()
```
Under this model the significant predictors are view_gain_count stream_time_mins

### Subquestion Four

```{r}
str(twitch)
```


```{r}
# # Example data preparation
# twitch$StreamTimeBin <- cut(twitch$stream_time_mins, breaks=quantile(twitch$stream_time_mins), include.lowest=TRUE)
# twitch$WatchTimeBin <- cut(twitch$watch_time_mins, breaks=quantile(twitch$watch_time_mins), include.lowest=TRUE)
# 
# # Create the heatmap
# plot_ly(twitch, x = ~StreamTimeBin, y = ~WatchTimeBin, type = 'heatmap', colors = 'Blues', showscale = TRUE)

p <- ggplot(twitch, aes(x=peak_view_count,y=avg_view_count)) + 
  geom_bin2d() +
  scale_color_viridis() +
  scale_fill_viridis()

ggplotly(p)
```

